version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=first-db-2024
      - MYSQL_USER=kru1l
      - MYSQL_PASSWORD=just1
      - MYSQL_ROOT_PASSWORD=super2
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: on-failure

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mongo-db-2024
      - MONGO_INITDB_ROOT_USERNAME=kru1l
      - MONGO_INITDB_ROOT_PASSWORD=just1
    volumes:
      - ./mongo-db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf